name: studia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.7.0
  build_runner: ^2.4.7
  intl: ^0.20.2
  devtools_extensions: ^0.3.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  path_provider: ^2.1.1
  path: ^1.9.0
  camera: ^0.11.1
  camera_android: ^0.10.10
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.5.3
  google_generative_ai: ^0.4.6
  chat_bubbles: ^1.7.0
  material_color_utilities: ^0.11.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.6
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.3.2
  dartz: ^0.10.1
  mockito: ^5.4.0
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: 0.5.32
  get_it: ^8.0.3 
  injectable: ^2.5.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  drift_dev: ^2.26.0
  freezed: ^3.0.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.4.7
  mocktail: ^1.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/curriculum/
    - assets/svg/
    - assets/svg/standard/
