name: studia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  freezed_annotation: 2.4.4
  json_annotation: ^4.7.0
  build_runner: ^2.4.7
  intl: ^0.20.2
  devtools_extensions: ^0.3.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  path_provider: ^2.1.1
  path: ^1.9.0
  camera: ^0.11.1
  camera_android: ^0.10.10
  http: ^1.1.0
  animated_text_kit: ^4.2.2
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.5.3
  google_generative_ai: ^0.4.6
  chat_bubbles: ^1.7.0
  material_color_utilities: ^0.11.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.6
  cloud_firestore: ^5.6.5
  firebase_database: ^11.3.4
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  get_it: ^7.6.0
  dio: ^5.3.2
  dartz: ^0.10.1

dev_dependencies:
  freezed: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages